const references = [
  "Been with Tucker since the beginning. I've seen him grow as a developer as well as support us through this journey. He was always helpful, supportive and kind. He was a great TL.",
  "When I was too tired to go forward, Tucker was there to provide mental strength to make me get back on track. When I have coding questions, Tucker shared his experience to help. I believe I was able to knock out each modules because Tucker was always there to support us. I thank him!",
  "a thousand thanks for (trying) to keep my head straight when it's backwards.",
  "great TL, always willing to help others, always happy and optimistic about any aspect of life. he's inspiring to others and wants to succeed with others. he's an awesome person and TL",
  "We had great pair programming this unit and awesome standups at the end of each day. Tucker has taught me how to be a good TL and I cannot wait for all of us to share our success stories. I wish him the best as he moves forward in his studies :)",
  "Tucker is always helpful and kind. He's great at offering us additional resources and is a great sense of support and guidance. He helps us feel better at the end of a hard day and is always listening to our feedback and takes it into account to help us better. Tucker is a great TL.",
  "Always super helpful and trying to get us where we need to be during the week. I appreciate the support and the fun we all have.",
  "great team lead goes above and beyond in helping each student.",
  "we should try polling some time management skills or goals we want and other practical career/ project related skills to learn together",
  "I have a lot of respect for Tucker, and how he juggles being a student as well as always being there to help us out. He's an awesome TL!!",
  "Super helpful and present. Tucker is getting really good at leading us through this challenging stuff.",
  "Tucker helped troubleshoot a lot of stuff for us this week, he also helped me troubleshoot the bug on the sprint challenge this week very quickly! Was really nice to have his support this week.",
  "Tucker is such a strong TL, he always is willing to help and keeps us all motivated and informed.",
  "Tucker was a huge help this week. He was there to support us with any questions we had about the projects and was a good emotional support as well.",
  "Tucker is a great TL! I'm grateful for my TL group as well and how Tucker helps us out whenever we ask a question.",
  "Great team lead, always optimistic, very helpful and motivating",
  "Tucker is always responsive and his good vibe make everyone feel supported and relaxed during standups!",
  "Tucker is very supportive and kind and because of his vibe, it fosters the same within our small group! We are all very happy with Tucker as our TL as well as the individuals in our group.",
  "Tucker has been an awesome TL! He makes everybody feel welcome, and adds extra links to our channel if we want more practice and other ways to learn. I really appreciate that!",
  "🐐",
  "He always helps the team and tries to put team together by making us exercise group activities. It helped me to understand coding better. I thank him.",
  "- looking forward to React routing struggles with you 😖, better sprint this time but I didn't feel there was enough time for test-driven developing with the questions and such, but this week definitely reflected the challenge well",
  "I've been really impressed with Tucker. He will help out when we need, and explains things clearly. He also never makes you feel like you ask a dumb question. He's a great Team Lead!",
  "give him a raise he's doing a great job, we need more TLs like him",
  "I was able to reduce verbosity on my code because he gave me coding tips during 1 on 1 review. In addition, when I was mentally tired, I was able to come back because he gave me strength. I thank him.",
  "Tucker provided a lot of extra assistance and support for us this week. Our standups are always so soothing after a hard day, and they are also fun and informative. I really enjoy our group.",
  "Tucker is a great leader and helps promote his kindness and sharing throughout the group.",
  "I know I'll never forget the stress that Lambda molded into a diamond . . . . but damn. 😌",
  "Tucker is a great Team Lead! He's very inspiring to me and the other members of my group",
  "great team lead, very optimistic, very uplifting and motivating, very helpful, happy camper",
  "Tucker does a good job of involving everyone in the stand up meetings, without making anyone feel uncomfortable. He also makes it apparent that he is willing to help any of us as much as we might need. He seems to really care about our success, which is awesome!",
  "He followed up with 1:1 meeting and group meeting and answered questions.",
  "Tucker is timely, responsive, and very helpful! I appreciate his friendly demeanor, generosity, and clarity of instruction.",
  "keep up the great work! your accepting and calm energy allows students to open up easily and feel understood."
];
